language: java
jdk:
- openjdk8
install: true
notifications:
  email: false
  on_success: change
  on_failure: always
  slack:
    rooms:
      secure: IaOcI9p2F9KB6tI+5HaMEiA1u6Dj77EoRGwUeJed3wKakqDxIkQdRpRqx1Ubk9JTN5uW/sLr9r5qHqV4upmCz3kMmuPvKp0GjWWrGlw5oxmHJ5qmqngy2Ht8DJC5nlVBQ0NdwmYj7KZpIvy/3+Ht+lP8ksC1uYrFIgs6hI4bctZywvBjuJNwbDYObcy+6xZI1UJ4Xh20ymX0zPGteZRYMnUe4mbkTwQVVT4uJ5VYMo68HjSuZEpJIeps/Ha3e7oWKauocxDmna+FoZjycaroCF3nHVoGJouFwNniTdlqDMs24OpCF1wObVRZHFL5NxkgfgYpxZCJIFajkFKlUEDhiElRnt/nJV/QnFcV6yqBt2duOJDPA5QItzRBZvcKrOt4+ckB/UQoKV2YmOLHg54RnKvc5cavVmYUik9uHXcp0yeNUudn/hXKB1tvgRts+97255Yt/YzK8mWX4N6fePqSg4GAQspj324OAzcdibwDeNLKg+xHBGUWy3gcPutbPmenTUZT2jv5qrWhbEcLutvzB52r+N8AY27wgjRA7zypuuHzGcuX9Ar8DdKUo+Cd6TwkVbxPxr4rq87a2c7C3sMjJnBhNr658ezNEy5GnDGmHIODE8jZBJUoVKQ9kJ39Jqn/ky6CB7Wj4LcDa2VzCYfdgHGm9YpnG19fdAzNGy7huD4=
